image: Visual Studio 2017

shallow_clone: true

services:
  - mysql
  
cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.MySql -c Release 
  - dotnet build Rebus.MySql.Tests -c Release 
