image: Visual Studio 2017

shallow_clone: true

services:
  - mysql

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

install:
  - ps: $env:MYSQL_PWD="Password12!"
  - ps: $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database rebus2_test;" --user=root'
  - ps: iex "& $cmd"

environment:
  REBUS_MYSQL: Server=localhost;Database=rebus2_test;Uid=root;Pwd=Password12!;


before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.MySql -c Release 
  - dotnet build Rebus.MySql.Tests -c Release 
